//-------------------------------------------------------------------------
// FullAdder_noparam.v
//-------------------------------------------------------------------------
// This file is generated by PyMTL SystemVerilog translation pass.

// PyMTL Component FullAdder Definition
// At /home/dzw/npu-playground/fifo/pymtl.py

module FullAdder_noparam
(
  input  logic [0:0] a ,
  input  logic [0:0] b ,
  input  logic [0:0] cin ,
  input  logic [0:0] clk ,
  output logic [0:0] cout ,
  input  logic [0:0] reset ,
  output logic [0:0] sum 
);

  // PyMTL Update Block Source
  // At /home/dzw/npu-playground/fifo/pymtl.py:14
  // @update
  // def upblk():
  //   s.sum  @= s.cin ^ s.a ^ s.b
  //   s.cout @= ( ( s.a ^ s.b ) & s.cin ) | ( s.a & s.b )
  
  always_comb begin : upblk
    sum = ( cin ^ a ) ^ b;
    cout = ( ( a ^ b ) & cin ) | ( a & b );
  end

endmodule
